/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'status' : BillStatus,
  'billDate' : bigint,
  'totalAmount' : number,
  'items' : Array<BillItem>,
  'paidAmount' : number,
  'supplierID' : bigint,
}
export interface BillItem {
  'quantity' : bigint,
  'medicineID' : bigint,
  'unitRate' : number,
}
export type BillStatus = { 'Paid' : null } |
  { 'Unpaid' : null } |
  { 'Partial' : null };
export interface DashboardStats {
  'totalStockValue' : number,
  'totalMedicineCount' : bigint,
  'lowStockCount' : bigint,
  'expiringSoonCount' : bigint,
}
export type Department = { 'OT' : null } |
  { 'ICU' : null } |
  { 'OPD' : null } |
  { 'Ward' : null } |
  { 'Emergency' : null };
export interface Distribution {
  'id' : bigint,
  'note' : string,
  'issuedDate' : bigint,
  'quantity' : bigint,
  'issuedBy' : string,
  'department' : Department,
  'medicineID' : bigint,
  'medicineName' : string,
}
export interface Medicine {
  'id' : bigint,
  'manufacturer' : string,
  'lowStockThreshold' : bigint,
  'expiryDate' : string,
  'name' : string,
  'quantity' : bigint,
  'batchNo' : string,
  'supplierID' : bigint,
  'unitRate' : number,
}
export interface Payment {
  'id' : bigint,
  'note' : string,
  'paymentDate' : bigint,
  'amount' : number,
  'billID' : bigint,
}
export interface Supplier {
  'id' : bigint,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBill' : ActorMethod<[Bill], bigint>,
  'addDistribution' : ActorMethod<[Distribution], bigint>,
  'addMedicine' : ActorMethod<[Medicine], bigint>,
  'addPayment' : ActorMethod<[Payment], bigint>,
  'addSupplier' : ActorMethod<[Supplier], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getBill' : ActorMethod<[bigint], Bill>,
  'getBillsBySupplier' : ActorMethod<[bigint], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDistribution' : ActorMethod<[bigint], Distribution>,
  'getDistributionsByDepartment' : ActorMethod<
    [Department],
    Array<Distribution>
  >,
  'getLowStockMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMedicine' : ActorMethod<[bigint], Medicine>,
  'getPayment' : ActorMethod<[bigint], Payment>,
  'getSupplier' : ActorMethod<[bigint], Supplier>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];