/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BillStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
  'Partial' : IDL.Null,
});
export const BillItem = IDL.Record({
  'quantity' : IDL.Nat,
  'medicineID' : IDL.Nat,
  'unitRate' : IDL.Float64,
});
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'status' : BillStatus,
  'billDate' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(BillItem),
  'paidAmount' : IDL.Float64,
  'supplierID' : IDL.Nat,
});
export const Department = IDL.Variant({
  'OT' : IDL.Null,
  'ICU' : IDL.Null,
  'OPD' : IDL.Null,
  'Ward' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const Distribution = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'issuedDate' : IDL.Int,
  'quantity' : IDL.Nat,
  'issuedBy' : IDL.Text,
  'department' : Department,
  'medicineID' : IDL.Nat,
  'medicineName' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'lowStockThreshold' : IDL.Nat,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'batchNo' : IDL.Text,
  'supplierID' : IDL.Nat,
  'unitRate' : IDL.Float64,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'paymentDate' : IDL.Int,
  'amount' : IDL.Float64,
  'billID' : IDL.Nat,
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalStockValue' : IDL.Float64,
  'totalMedicineCount' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'expiringSoonCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBill' : IDL.Func([Bill], [IDL.Nat], []),
  'addDistribution' : IDL.Func([Distribution], [IDL.Nat], []),
  'addMedicine' : IDL.Func([Medicine], [IDL.Nat], []),
  'addPayment' : IDL.Func([Payment], [IDL.Nat], []),
  'addSupplier' : IDL.Func([Supplier], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
  'getBillsBySupplier' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDistribution' : IDL.Func([IDL.Nat], [Distribution], ['query']),
  'getDistributionsByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(Distribution)],
      ['query'],
    ),
  'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
  'getSupplier' : IDL.Func([IDL.Nat], [Supplier], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BillStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
    'Partial' : IDL.Null,
  });
  const BillItem = IDL.Record({
    'quantity' : IDL.Nat,
    'medicineID' : IDL.Nat,
    'unitRate' : IDL.Float64,
  });
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'status' : BillStatus,
    'billDate' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(BillItem),
    'paidAmount' : IDL.Float64,
    'supplierID' : IDL.Nat,
  });
  const Department = IDL.Variant({
    'OT' : IDL.Null,
    'ICU' : IDL.Null,
    'OPD' : IDL.Null,
    'Ward' : IDL.Null,
    'Emergency' : IDL.Null,
  });
  const Distribution = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'issuedDate' : IDL.Int,
    'quantity' : IDL.Nat,
    'issuedBy' : IDL.Text,
    'department' : Department,
    'medicineID' : IDL.Nat,
    'medicineName' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'lowStockThreshold' : IDL.Nat,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'batchNo' : IDL.Text,
    'supplierID' : IDL.Nat,
    'unitRate' : IDL.Float64,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'paymentDate' : IDL.Int,
    'amount' : IDL.Float64,
    'billID' : IDL.Nat,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalStockValue' : IDL.Float64,
    'totalMedicineCount' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'expiringSoonCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBill' : IDL.Func([Bill], [IDL.Nat], []),
    'addDistribution' : IDL.Func([Distribution], [IDL.Nat], []),
    'addMedicine' : IDL.Func([Medicine], [IDL.Nat], []),
    'addPayment' : IDL.Func([Payment], [IDL.Nat], []),
    'addSupplier' : IDL.Func([Supplier], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
    'getBillsBySupplier' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDistribution' : IDL.Func([IDL.Nat], [Distribution], ['query']),
    'getDistributionsByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(Distribution)],
        ['query'],
      ),
    'getLowStockMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
    'getSupplier' : IDL.Func([IDL.Nat], [Supplier], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };